language: go

go:
  - 1.12

services:
  - mysql
  - redis-server

env:
  DB_DRIVER: mysql
  DB_HOST: 127.0.0.1
  DB_PORT: 3306
  DB_DATABASE: test
  DB_USERNAME: root
  REDIS_URL: redis://redis.vcap.me:6379
  REDIS_MAX_IDLE: 10
  REDIS_MAX_ACTIVE: 50
  REDIS_IDLE_TIMEOUT: 180

before_install:
  - mysql -e 'CREATE DATABASE test;'

script:
  - go test -v -cover -test.count=1  ./...
