language: go

go:
  - 1.16

services:
  - mysql
  - postgresql
  - redis-server

env:
  global:
    - MYSQL_DATABASE_URL='mysql://root@tcp(db.vcap.me:3306)/go-sdk_test?charset=utf8'
    - POSTGRES_DATABASE_URL=postgres://postgres@db.vcap.me:5432/go-sdk_test?sslmode=disable
    - REDIS_URL=redis://redis.vcap.me:6379
    - REDIS_MAX_IDLE=10
    - REDIS_MAX_ACTIVE=50
    - REDIS_IDLE_TIMEOUT=180

script:
  - go test -v -cover -test.count=1  ./...
